spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      
      properties:
        spring:
          json:
            trusted:
              packages: com.producer.dto
         
          deserializer:
            value:
              delegate:
                class:  org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-event-group
      auto-offset-reset: earliest