server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Meghana@7
    url: jdbc:mysql://localhost:3306/meghana1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: mobile-api
